service: rhibhus
provider:
    name: aws
    runtime: nodejs18.x
    lambdaHashingVersion: "20201221"
    timeout: 29
    region: ap-south-1
    stage: ${opt:stage}
    deploymentBucket:
        name: rhibhus-serverlessdeploymentbucket
    environment:
        DB_PREFIX: ${self:provider.stage}_
        STAGE: ${self:provider.stage}
        ACCESS_KEY_ID: ${file(config/${self:provider.stage}-config.yml):data.aws_credentials.ACCESS_KEY_ID}
        SECRET_ACCESS_KEY: ${file(config/${self:provider.stage}-config.yml):data.aws_credentials.SECRET_ACCESS_KEY}
        SECRET_KEY: ${file(config/${self:provider.stage}-config.yml):data.aws_credentials.SECRET_KEY}
        REGION: ${file(config/${self:provider.stage}-config.yml):data.aws_credentials.REGION}
        ACCOUNT_NUMBER: ${file(config/${self:provider.stage}-config.yml):data.aws_credentials.ACCOUNT_NUMBER}
        BUCKET_NAME: ${self:provider.stage}-rhibhus-server
        NODE_ENV: ${self:provider.stage}

    iam:
        role:
            statements:
                - Effect: Allow
                  Action:
                      - dynamodb:Query
                      - dynamodb:Scan
                      - dynamodb:GetItem
                      - dynamodb:PutItem
                      - dynamodb:UpdateItem
                      - dynamodb:DeleteItem
                      - dynamodb:CreateTable
                  Resource:
                      - "*"
                - Effect: Allow
                  Action:
                      - sns:"*"
                  Resource:
                      - "*"

functions:
    rhibhus-lambda:
        handler: handler.rhibhus_server
        events:
            - http:
                  path: /
                  method: GET
                  cors: true
            - http:
                  path: /health
                  method: GET
                  cors: true
            - http:
                  path: /v1/userLogin
                  method: POST
                  cors: true
            - http:
                  path: /v1/userRegister
                  method: POST
                  cors: true
